model_name: AE

seed: 42

split_dir: ./data/splits

target_size: !<tag:yaml.org,2002:seq> [128,128]
batch_size: 64

lr: 0.001
num_epochs: 10
in_chan: 1
out_chan: 128
load_ae: False
ae_lr: 0.001
nae_lr: 1.0e-5
nae_epoch: 1
ae_epoch: 10
arch: given
sampler:
  x_stepsize: 20
  z_stepsize: 1
  x_step: 50
  z_step: 20